'use strict';
const express=require('express'),cors=require('cors'),rateLimit=require('express-rate-limit'),archiver=require('archiver');
const {spawn}=require('child_process'),{mkdtemp,rm,readdir,stat}=require('fs/promises'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const app=express(),PORT=Number(process.env.MULTIMP3_PORT||4783),HOST=process.env.MULTIMP3_HOST||'127.0.0.1';
const YTDLP=process.env.YT_DLP_PATH||'yt-dlp',FFMPEG=process.env.FFMPEG_PATH||'ffmpeg';
const allowedOrigins=(process.env.MULTIMP3_ALLOWED_ORIGINS||'http://127.0.0.1:4173,http://localhost:4173').split(',').map(x=>x.trim()).filter(Boolean);
app.disable('x-powered-by');app.use((_q,r,n)=>{r.setHeader('Access-Control-Allow-Private-Network','true');n()});app.use(express.json({limit:'128kb'}));app.use(cors({origin(o,cb){if(!o||allowedOrigins.includes('*')||allowedOrigins.includes(o))return cb(null,true);cb(new Error('Origin is not allowed.'))}}));app.use('/api',rateLimit({windowMs:60_000,limit:40,standardHeaders:true,legacyHeaders:false}));
const safe=s=>(s||'track').normalize('NFKC').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/g,'').slice(0,120)||'track';
function youtube(raw){let u;try{u=new URL(raw)}catch{throw new Error('Invalid URL.')}if(!['youtube.com','www.youtube.com','music.youtube.com','youtu.be'].includes(u.hostname))throw new Error('Only YouTube links are supported.');if(u.protocol!=='https:')throw new Error('HTTPS is required.');return u.toString()}
function run(exe,args,{timeout=120_000}={}){return new Promise((resolve,reject)=>{const p=spawn(exe,args,{windowsHide:true,stdio:['ignore','pipe','pipe']}),out=[],err=[];let size=0;const timer=setTimeout(()=>{p.kill();reject(new Error('Processing timed out.'))},timeout);p.stdout.on('data',b=>{size+=b.length;if(size<8_000_000)out.push(b)});p.stderr.on('data',b=>err.push(b));p.on('error',reject);p.on('close',code=>{clearTimeout(timer);code===0?resolve(Buffer.concat(out).toString('utf8')):reject(new Error(Buffer.concat(err).toString('utf8').slice(-1200)||`Processor exited with ${code}`))})})}
async function info(url){const raw=await run(YTDLP,['--dump-single-json','--flat-playlist','--no-warnings','--no-playlist',youtube(url)]);const x=JSON.parse(raw);return{url,title:x.title||x.fulltitle,creator:x.channel||x.uploader,duration:x.duration?new Date(x.duration*1000).toISOString().slice(11,19).replace(/^00:/,'' ):'',thumbnail:x.thumbnail||x.thumbnails?.at(-1)?.url||''}}
app.get('/api/health',async(_q,r)=>{try{await Promise.all([run(YTDLP,['--version'],{timeout:10_000}),run(FFMPEG,['-version'],{timeout:10_000})]);r.json({ok:true,service:'MultiMP3',version:'1.3.0'})}catch(e){r.status(503).json({ok:false,error:e.message})}});
app.post('/api/info',async(req,res)=>{const urls=Array.isArray(req.body.urls)?req.body.urls.slice(0,50):[];if(!urls.length)return res.status(400).json({error:'Provide 1–50 URLs.'});const items=[];for(const url of urls){try{items.push(await info(url))}catch(e){items.push({url,error:e.message})}}res.json({items})});
async function convert(track,quality,dir,index){const url=youtube(track.url),base=`${String(index+1).padStart(3,'0')} - ${safe(track.title)}`,template=path.join(dir,base+'.%(ext)s');const q=quality==='best'?'0':String(Number(quality)||192);await run(YTDLP,['--no-playlist','--no-warnings','-x','--audio-format','mp3','--audio-quality',q,'--ffmpeg-location',FFMPEG,'-o',template,url],{timeout:15*60_000});const names=await readdir(dir);const name=names.find(n=>n.startsWith(base+'.')&&n.endsWith('.mp3'));if(!name)throw new Error('Converted file was not created.');return path.join(dir,name)}
let conversionTail=Promise.resolve();function exclusive(job){const next=conversionTail.then(job,job);conversionTail=next.catch(()=>{});return next}
app.post('/api/download',async(req,res)=>{let dir;try{dir=await mkdtemp(path.join(os.tmpdir(),'multimp3-'));const file=await exclusive(()=>convert({url:req.body.url,title:req.body.title||'track'},req.body.quality,dir,0));res.download(file,safe(req.body.title||'track')+'.mp3',()=>rm(dir,{recursive:true,force:true}))}catch(e){if(dir)await rm(dir,{recursive:true,force:true});res.status(400).json({error:e.message})}});
app.post('/api/export',async(req,res)=>{const albums=Array.isArray(req.body.albums)?req.body.albums.slice(0,50):[];const count=albums.reduce((n,a)=>n+(Array.isArray(a.tracks)?a.tracks.length:0),0);if(!count||count>250)return res.status(400).json({error:'Archive must contain 1–250 tracks.'});let dir=await mkdtemp(path.join(os.tmpdir(),'multimp3-export-'));try{const completed=await exclusive(async()=>{const done=[];for(const album of albums){const folder=path.join(dir,safe(album.name||'Unsorted'));await fs.promises.mkdir(folder,{recursive:true});for(const track of (album.tracks||[])){try{done.push(await convert(track,req.body.quality,folder,done.length))}catch(e){done.push({error:e.message,title:track.title})}}}return done});if(!completed.some(x=>typeof x==='string'))throw new Error('No tracks could be converted.');res.attachment(safe(req.body.filename||'MultiMP3_Site_Albums.zip'));const zip=archiver('zip',{zlib:{level:6}});zip.on('error',e=>res.destroy(e));res.on('close',()=>rm(dir,{recursive:true,force:true}));zip.pipe(res);zip.directory(dir,false);await zip.finalize()}catch(e){await rm(dir,{recursive:true,force:true});res.status(400).json({error:e.message})}});
app.use((e,_q,r,_n)=>r.status(400).json({error:e.message||'Request failed.'}));const server=app.listen(PORT,HOST,()=>console.log(`MultiMP3 backend listening on http://${HOST}:${PORT}`));function close(){server.close(()=>process.exit(0))}process.on('SIGINT',close);process.on('SIGTERM',close);
